# Generated by Django 5.1.2 on 2024-10-16 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='other_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_involved_in', to='a_wallet.wallet'),
        ),
    ]
