# Generated by Django 5.1.2 on 2024-10-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_wallet', '0004_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
