# Generated by Django 5.1.2 on 2024-10-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_wallet', '0005_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=6),
        ),
    ]
