# Generated by Django 5.1.2 on 2024-10-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_wallet', '0006_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('deposit', 'Deposit')], default='debit', max_length=10),
        ),
    ]
