# Generated by Django 5.1.2 on 2024-10-18 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_expense_items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('used_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weeks',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('item_involved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements_involved_in', to='a_expense_items.expenseitem')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='a_weekly_budget.week')),
            ],
            options={
                'db_table': 'statements',
            },
        ),
        migrations.CreateModel(
            name='WeekItemAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_item_association', to='a_expense_items.expenseitem')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_item_association', to='a_weekly_budget.week')),
            ],
            options={
                'db_table': 'week_item_association',
            },
        ),
        migrations.AddField(
            model_name='week',
            name='expense_items',
            field=models.ManyToManyField(blank=True, related_name='weeks', through='a_weekly_budget.WeekItemAssociation', to='a_expense_items.expenseitem'),
        ),
    ]
