# Generated by Django 5.1.2 on 2024-10-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_weekly_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
