# Generated by Django 5.1.2 on 2024-10-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_weekly_budget', '0002_alter_statement_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ('created_at',)},
        ),
    ]
