# Generated by Django 5.1.2 on 2024-10-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_expense_items', '0001_initial'),
        ('a_weekly_budget', '0003_alter_week_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='item_involved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements_involved_in', to='a_expense_items.expenseitem'),
        ),
    ]
