# Generated by Django 5.1.2 on 2024-11-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_weekly_budget', '0004_alter_statement_item_involved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
