# Generated by Django 5.1.2 on 2024-11-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_weekly_budget', '0005_alter_week_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ('-created_at',)},
        ),
    ]
