# Generated by Django 5.1.2 on 2024-10-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_profile', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
