from .MyWalletsView import MyWalletsView
from .TransferWalletFundsView import TransferWalletFundsView
from .CreateWalletView import CreateWalletView
from .DeleteWalletView import DeleteWalletView
from .WalletTransactionsView import WalletTransactionsView
from .WalletDetailView import WalletDetailView
from .DepositFundsView import DepositFundsView